### ISSUE TITLE
behave tests: Avoid deletes in "environment.py"

### ISSUE THREAD

**Issue by jenisys** [arnemertz/fix#3]
I was just looking over [test/behave/environment.py](https://github.com/arnemertz/fix/blob/master/test/behave/environment.py#L13l). 
Just a hint. I think you should not delete the ``context`` and ``scenario`` objects that are used by ``behave`` in your hook implementations. You are basically messing with behave's test runner resources.

**Comment by arnemertz** [comment]
Thanks for the hint. I am pretty new to Python, this is just a way to silence "unused arguments" warnings I found online. I will look into what `del` really does.
